apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: service-bus
type: Opaque
stringData:
  user: "lab"
  password: "AksLab!Rabbit1"
  amqp-url: "amqp://lab:AksLab!Rabbit1@rabbitmq.service-bus.svc.cluster.local:5672"
