apiVersion: v1
kind: Service
metadata:
  name: servicebus
  namespace: service-bus
spec:
  selector:
    app: servicebus
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 5300
      targetPort: 5300
