apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: cosmos-db
type: Opaque
stringData:
  username: "admin"
  password: "AksLab!Mongo1"
  connection-string: "mongodb://admin:AksLab%21Mongo1@mongodb.cosmos-db.svc.cluster.local:27017"
