apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrepository.yaml
  - helmrelease.yaml
  # ingress.yaml is applied separately by lab-feature.sh once hubble-ui Service
  # is created by the Cilium chart.
