apiVersion: v1
kind: Service
metadata:
  name: cosmosdb
  namespace: cosmos-db
spec:
  type: LoadBalancer
  loadBalancerIP: 172.16.3.6
  selector:
    app: cosmosdb
  ports:
    - name: gateway
      port: 8081
      targetPort: 8081
    - name: direct1
      port: 10251
      targetPort: 10251
    - name: direct2
      port: 10252
      targetPort: 10252
    - name: direct3
      port: 10253
      targetPort: 10253
    - name: direct4
      port: 10254
      targetPort: 10254
