
# Azure Entra Client ID Secret (for local POC only)
apiVersion: v1
kind: Secret
metadata:
  name: client-id-secret
  namespace: jeragm-poc
  labels:
    app: argo-ui
stringData:
  # TODO: Replace with your Azure App Registration Client ID for local testing
  client-id-key: "<your-azure-client-id>"

---

# Azure Entra Client Secret (for local POC only)
apiVersion: v1
kind: Secret
metadata:
  name: client-secret-secret
  namespace: jeragm-poc
  labels:
    app: argo-ui
stringData:
  # TODO: Replace with your Azure App Registration Client Secret for local testing
  client-secret-key: "<your-azure-client-secret>"