apiVersion: v1
kind: Secret
metadata:
  name: bloods-config
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  SQL_CONNECTION_STRING: {{ .Values.config.sqlConnectionString | quote }}
  BLOB_CONNECTION_STRING: {{ .Values.config.blobConnectionString | quote }}
