FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY src/Web/ ./Web/
RUN dotnet publish Web/IncidentHub.Web.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
RUN useradd -u 10001 -r app && chown app /app
USER app
COPY --from=build --chown=app /app/publish .
EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8080
ENTRYPOINT ["dotnet", "IncidentHub.Web.dll"]
