apiVersion: v1
kind: ServiceAccount
metadata:
  name: calendar-uploader
  namespace: ddh-poc
  labels:
    app: calendar-uploader
    managed-by: argo-workflows

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: calendar-uploader-wftaskresults
  namespace: ddh-poc
rules:
- apiGroups: ["argoproj.io"]
  resources: ["workflowtaskresults"]
  verbs: ["create","patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: calendar-uploader-wftaskresults
  namespace: ddh-poc
subjects:
- kind: ServiceAccount
  name: calendar-uploader
  namespace: ddh-poc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: calendar-uploader-wftaskresults
