{{- if .Values.ingress.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: incidenthub-tls
  namespace: {{ .Values.namespace }}
spec:
  secretName: {{ .Values.ingress.tlsSecret }}
  issuerRef:
    name: lab-ca
    kind: ClusterIssuer
  commonName: {{ .Values.ingress.host }}
  dnsNames:
    - {{ .Values.ingress.host }}
  duration: 720h
  renewBefore: 240h
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: incidenthub
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: lab-ca
    nginx.ingress.kubernetes.io/auth-url: "https://oauth2-proxy.oauth2-proxy.svc.cluster.local/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://oauth2.aks-lab.local/oauth2/start?rd=$escaped_request_uri"
spec:
  ingressClassName: nginx
  tls:
    - hosts: [{{ .Values.ingress.host }}]
      secretName: {{ .Values.ingress.tlsSecret }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: incidenthub-web
                port: { number: 80 }
{{- end }}
