{{- if not .Values.vault.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: incidenthub-config
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  SQL_CONNECTION_STRING: {{ .Values.config.sqlConnectionString | quote }}
  BLOB_CONNECTION_STRING: {{ .Values.config.blobConnectionString | quote }}
  SERVICEBUS_CONNECTION_STRING: {{ .Values.config.serviceBusConnectionString | quote }}
  COSMOS_CONNECTION_STRING: {{ .Values.config.cosmosConnectionString | quote }}
{{- end }}
