apiVersion: apps/v1
kind: Deployment
metadata:
  name: incidenthub-worker
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "incidenthub.labels" . | nindent 4 }}
    component: worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels: { app.kubernetes.io/name: incidenthub, component: worker }
  template:
    metadata:
      labels: { app.kubernetes.io/name: incidenthub, component: worker }
    spec:
      serviceAccountName: incidenthub
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        seccompProfile: { type: RuntimeDefault }
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}-worker:{{ .Values.image.workerTag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef: { name: incidenthub-config }
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: { drop: ["ALL"] }
