apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: ddh-calendar-uploader-cron
  namespace: ddh-poc
  labels:
    app: calendar-uploader
spec:
  schedules:
    - "*/20 * * * *"
  timezone: "Asia/Singapore"
  concurrencyPolicy: "Replace"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  workflowSpec:
    workflowTemplateRef:
      name: ddh-calendar-uploader-common-template
    arguments:
      parameters:
        - name: isManualRun
          value: "false"  # Override to automated mode for scheduled runs
