apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: container-registry
spec:
  type: LoadBalancer
  loadBalancerIP: 172.16.3.5
  selector:
    app: registry
  ports:
    - name: registry
      port: 5000
      targetPort: 5000
