#!/usr/bin/env bash
# lab-publish.sh — make the lab reachable from other machines on the LAN
# (e.g. the MacBook) via the Mac Pro's host IP.
#
# Model (see docs/network-setup.md): the MacBook resolves *.aks-lab.local to the
# Mac Pro's LAN IP; the Mac Pro republishes the ports that `minikube tunnel`
# binds on loopback out to its Ethernet interface with socat forwarders managed
# by a launchd daemon. No router static routes, no reliance on the nested Colima
# bridge. The K8s API (8443) and Vault (8200) already bind 0.0.0.0, so they only
# need DNS + (for kubectl) an external kubeconfig.
#
# Idempotent. Re-run after enabling/disabling components to refresh the port set.
set -uo pipefail
export PATH="/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/local/bin:/opt/local/sbin:/opt/homebrew/bin:$PATH"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
PROFILE="${LAB_PROFILE:-aks-lab}"

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'
CYAN='\033[0;36m'; BOLD='\033[1m'; DIM='\033[2m'; RESET='\033[0m'
log()     { echo -e "${CYAN}${BOLD}[lab]${RESET} $*"; }
success() { echo -e "${GREEN}${BOLD}[✓]${RESET} $*"; }
warn()    { echo -e "${YELLOW}${BOLD}[!]${RESET} $*"; }
error()   { echo -e "${RED}${BOLD}[✗]${RESET} $*" >&2; exit 1; }

# shellcheck source=lib-common.sh
source "$SCRIPT_DIR/lib-common.sh"
cd "$REPO_ROOT" || exit 1
lab_load_features ".lab-state.json"

FORWARD_WRAPPER="/usr/local/bin/lab-publish-forward.sh"
FORWARD_PLIST="/Library/LaunchDaemons/com.lab.publish.plist"
DNSMASQ_DIR="$(lab_brew_prefix)/etc/dnsmasq.d"
KUBECONFIG_OUT="/tmp/aks-lab-kubeconfig.yaml"

# ── 1. Host IP ───────────────────────────────────────────────────────────────
LAB_HOST_IP="${LAB_HOST_IP:-$(route -n get default 2>/dev/null | awk '/interface:/{print $2}' | xargs -I{} ipconfig getifaddr {} 2>/dev/null)}"
[[ -n "$LAB_HOST_IP" && "$LAB_HOST_IP" != "127.0.0.1" ]] \
  || error "Could not determine this Mac's LAN IP. Set a static IP / DHCP reservation, then re-run (or pass LAB_HOST_IP=...)."
log "Publishing the lab on host IP ${BOLD}${LAB_HOST_IP}${RESET}"

# ── 2. Which ports to republish ──────────────────────────────────────────────
# 80/443 = NGINX ingress (all *.aks-lab.local web UIs, routed by Host header).
# The non-HTTP services are only published when their feature is enabled.
PORTS=(80 443)
feature_enabled azure-sql          && PORTS+=(1433)
feature_enabled container-registry && PORTS+=(5000)
feature_enabled service-bus        && PORTS+=(5672)
feature_enabled cosmos-db          && PORTS+=(8081)
feature_enabled azurite            && PORTS+=(10000 10001 10002)

# ── 3. Verify what minikube tunnel actually binds on loopback ────────────────
# The whole model assumes the tunnel exposes these on 127.0.0.1. Confirm before
# forwarding so we don't publish dead ports. (This is the one behaviour that
# must be checked empirically under the Colima docker driver.)
log "Checking which ports the tunnel is serving on 127.0.0.1..."
_missing=()
for _p in "${PORTS[@]}"; do
  if ! lsof -nP -iTCP@127.0.0.1:"$_p" -sTCP:LISTEN >/dev/null 2>&1; then
    _missing+=("$_p")
  fi
done
if [[ ${#_missing[@]} -gt 0 ]]; then
  warn "Not listening on 127.0.0.1 for: ${_missing[*]}"
  warn "  Is the cluster up and 'minikube tunnel' running? (./aks-lab resume)"
  warn "  Forwarders for those ports will start but stay idle until the tunnel binds them."
fi

# ── 4. socat forwarders (LAN IP:port → 127.0.0.1:port) via launchd ───────────
if ! command -v socat >/dev/null 2>&1; then
  error "socat is required to republish loopback ports to the LAN.
  Install it:  sudo port install socat   (macOS 12)   or   brew install socat
  Then re-run: ./aks-lab publish"
fi
_SOCAT="$(command -v socat)"

log "Installing port-forwarder daemon for: ${PORTS[*]}"
sudo tee "$FORWARD_WRAPPER" >/dev/null <<WRAPPER
#!/bin/bash
# Generated by scripts/lab-publish.sh — republishes loopback ports to the LAN.
# One socat per port: <LAB_HOST_IP>:PORT → 127.0.0.1:PORT.
SOCAT="${_SOCAT}"
HOST_IP="${LAB_HOST_IP}"
PORTS="${PORTS[*]}"
for p in \$PORTS; do
  "\$SOCAT" TCP-LISTEN:\$p,bind=\$HOST_IP,fork,reuseaddr TCP:127.0.0.1:\$p &
done
wait
WRAPPER
sudo chmod +x "$FORWARD_WRAPPER"

sudo tee "$FORWARD_PLIST" >/dev/null <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>            <string>com.lab.publish</string>
  <key>ProgramArguments</key> <array><string>${FORWARD_WRAPPER}</string></array>
  <key>RunAtLoad</key>        <true/>
  <key>KeepAlive</key>        <true/>
  <key>ThrottleInterval</key> <integer>10</integer>
  <key>StandardOutPath</key>  <string>/var/log/lab-publish.log</string>
  <key>StandardErrorPath</key><string>/var/log/lab-publish.log</string>
</dict>
</plist>
PLIST

sudo launchctl bootout system/com.lab.publish 2>/dev/null || true
if sudo launchctl bootstrap system "$FORWARD_PLIST" 2>/dev/null; then
  success "Forwarder daemon running — ${LAB_HOST_IP}:{${PORTS[*]// /,}} → 127.0.0.1"
else
  warn "Could not (re)load the forwarder daemon — check: sudo launchctl print system/com.lab.publish"
fi

# ── 5. dnsmasq: answer *.aks-lab.local with the host IP for LAN clients ──────
# Generated from the host IP so the MacBook reaches the Mac Pro (which then
# forwards via the socat daemon). The Mac Pro reaches its own LAN IP fine, so
# local browsing keeps working with this same config.
SAMBA_IP=$(_lima_ip samba-ad 2>/dev/null || true)
log "Writing dnsmasq LAN config to ${DNSMASQ_DIR}/aks-lab.conf..."
sudo mkdir -p "$DNSMASQ_DIR"
{
  echo "# Generated by scripts/lab-publish.sh — *.aks-lab.local → Mac Pro host IP."
  echo "address=/aks-lab.local/${LAB_HOST_IP}"
  if [[ -n "$SAMBA_IP" ]]; then
    echo "address=/corp.internal/${SAMBA_IP}"
    echo "server=/corp.internal/${SAMBA_IP}"
  fi
} | sudo tee "${DNSMASQ_DIR}/aks-lab.conf" >/dev/null
echo "nameserver 127.0.0.1" | sudo tee /etc/resolver/aks-lab.local >/dev/null
sudo brew services restart dnsmasq 2>/dev/null \
  || sudo "$(lab_brew_prefix)/bin/brew" services restart dnsmasq 2>/dev/null \
  || warn "Could not restart dnsmasq — restart it manually so the new config loads"
if lab_dnsmasq_answering; then
  success "dnsmasq answering — *.aks-lab.local → ${LAB_HOST_IP}"
else
  warn "dnsmasq not answering on 127.0.0.1:53 yet — check: sudo brew services list | grep dnsmasq"
fi

# ── 6. External kubeconfig for the MacBook ───────────────────────────────────
if kubectl config view --minify --context "$PROFILE" &>/dev/null; then
  log "Generating external kubeconfig (server → https://${LAB_HOST_IP}:8443)..."
  kubectl --context "$PROFILE" config view --minify --flatten \
    | sed "s#server: https://[0-9.]*:8443#server: https://${LAB_HOST_IP}:8443#" \
    > "$KUBECONFIG_OUT" 2>/dev/null \
    && success "External kubeconfig: ${KUBECONFIG_OUT}" \
    || warn "Could not generate external kubeconfig — is the cluster up?"
fi

# ── 7. MacBook-side instructions (the only manual steps) ─────────────────────
cat <<EOF

  ${BOLD}On the MacBook (one-time):${RESET}
    ${CYAN}sudo mkdir -p /etc/resolver${RESET}
    ${CYAN}echo "nameserver ${LAB_HOST_IP}" | sudo tee /etc/resolver/aks-lab.local${RESET}$( [[ -n "$SAMBA_IP" ]] && printf '\n    %becho "nameserver %s" | sudo tee /etc/resolver/corp.internal%b' "$CYAN" "$LAB_HOST_IP" "$RESET" )
    ${CYAN}scp $(whoami)@${LAB_HOST_IP}:${KUBECONFIG_OUT} ~/.kube/aks-lab-config${RESET}
    ${CYAN}KUBECONFIG=~/.kube/aks-lab-config kubectl get nodes${RESET}

  ${DIM}Then browse http://grafana.aks-lab.local etc. If the macOS firewall is on,${RESET}
  ${DIM}allow incoming connections for socat, dnsmasq, and vault (or disable it to test).${RESET}
  ${DIM}Full guide: docs/network-setup.md${RESET}

EOF
success "Lab published on the LAN via ${LAB_HOST_IP}"
