apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "blob-explorer.fullname" . }}
  labels:
    {{- include "blob-explorer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "blob-explorer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "blob-explorer.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: blob-explorer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: AZURE_STORAGE_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: {{ include "blob-explorer.fullname" . }}-storage
                  key: connection-string
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 15
