apiVersion: v1
kind: Secret
metadata:
  name: {{ include "blob-explorer.fullname" . }}-storage
  labels:
    {{- include "blob-explorer.labels" . | nindent 4 }}
type: Opaque
stringData:
  connection-string: {{ .Values.azureStorage.connectionString | quote }}
